version: '3.9'

services:

#uso immagine ufficiale per mySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  #uso l'immagine che ho creato nel dockerfile
  ms-user:
    build: .
    container_name: ms-user
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      #mySQL non è in localhost, docker crea una rete interna e risolve automaticamente i nomi (mysql)
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms_user_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

#predispone un volume (spazio in memoria) per il databse
volumes:
  mysql_data: